### ISSUE TITLE
Issue on page /chapters/01-1/4-learn-how-to-think.html

### ISSUE THREAD

**Issue by tobiaspfitzner** [BZoennchen/ct-book#1]
Hallo, 
ich bin mir nicht sicher, aber ich glaube ich hab einen Fehler gefunden. Dort wo man den Preis des Balles eintippen soll ist der Preis des Schlägers als richtig und der Preis des Balles als falsch hinterlegt. Die Frage ist doch, wie teuer der Ball ist und nicht wie teuer der Schläger ist. 
VG
![image](https://github.com/user-attachments/assets/5ec72f65-7b18-4747-8b5a-90d7f8047f41)
![image](https://github.com/user-attachments/assets/408c9c84-33fc-401b-82de-bb616590327e)

**Comment by BZoennchen** [comment]
Absolut das war natürlich falsch. Sollte nun richtig sein. Danke für den Hinweis. Bitte gerne weitere Fehler melden!
