### ISSUE TITLE
Issue on page /chapters/01-3/2-formalizing-thought.html

### ISSUE THREAD

**Issue by nicholasiliou** [BZoennchen/ct-book#2]
Schreibfehler in 3.2.2:
"Für ganze Zahlen berechnet der Algorithmus den größten gemeinsamen **Teilers** gcd(a,b) zweier natürlicher Zahlen [...]"
![image](https://github.com/user-attachments/assets/bb7fc351-6362-46e3-b9e8-a8f062fcbefd)

**Comment by BZoennchen** [comment]
Changed "Teilers" to "Teiler". Thx for reporting.
